parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Domain/'
            - '../src/Application/Request/'
            - '../src/Application/Response/'
            - '../src/Infrastructure/Persistence/Type/'
            - '../src/Infrastructure/Persistence/Mapping/'
            - '../src/Kernel.php'

    App\UI\Rest\Controller\:
        resource: '../src/UI/Rest/Controller/*Controller*'
        tags: ['controller.service_arguments']

    App\Domain\ResponseBuilder\ResponseBuilderInterface: '@App\Infrastructure\ResponseBuilder\ResponseBuilder'

    App\UI\Rest\Controller\Unit\ArgumentResolver\UnitIdArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver}

    App\UI\Rest\Controller\Category\ArgumentResolver\CategoryArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver}

    App\UI\Rest\Controller\Category\ArgumentResolver\CategoryIdArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver}

    App\UI\Rest\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }