parameters:
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Domain/'
            - '../src/Application/Request/'
            - '../src/Application/Response/'
            - '../src/Infrastructure/Persistence/Type/'
            - '../src/Infrastructure/Persistence/Mapping/'
            - '../src/Kernel.php'

    App\UI\Rest\Controller\:
        resource: '../src/UI/Rest/Controller/*Controller*'
        tags: ['controller.service_arguments']

    App\Domain\ResponseBuilder\ResponseBuilderInterface: '@App\Infrastructure\ResponseBuilder\ResponseBuilder'

    App\UI\Rest\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    tseho.doctrine_assigned_identity.listener:
        class: Tseho\DoctrineAssignedIdentity\EventListener\AssignedIdentityListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist }
