parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\UI\Controller:
        resource: '../src/UI/Controller/'
        tags: ['controller.service_arguments']
