parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Domain/'
            - '../src/Application/Request/'
            - '../src/Application/Response/'
            - '../src/Infrastructure/Persistence/Type/'
            - '../src/Infrastructure/Persistence/Mapping/'
            - '../src/Kernel.php'
            - '../src/tests/'

    App\UI\Rest\Controller\:
        resource: '../src/UI/Rest/Controller/*'
        calls:
            - method: setContainer
              arguments: ['@service_container']
