doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            unicode_string: App\Infrastructure\Persistence\Type\UnicodeStringType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Mapping'
                prefix: App\Domain\Entity
