framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    http_method_override: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    serializer:
        enable_annotations: false
