monolog:
    channels: [deprecation]
    handlers:
        main:
            type: stream
            path: php://stdout
            level: debug
            channels: ["!event", "!deprecation"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
